DefaultContentLanguage = "en"
author = "Anonymous"
baseURL = "/"
copyright = ""
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
languageCode = "en"
paginate = 3
theme = "casper3"
title = "Processing Stochasticities"
[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 10
[[menu.main]]
identifier = "Projects"
name = "Projects"
url = "/Projects/"
weight = 10
[[menu.main]]
identifier = "Articles"
name = "Articles"
url = "/Articles/"
weight = 10
description = "Processing Stochasticities"
facebook = ""
github = "https://github.com/joshuapurtell"
logo = "/images/test_logo.png"
mainSections = ["math", "post"]
twitter = "https://twitter.com/quantumwitty"
[privacy.instagram]
disabled = false
simple = true
[privacy.twitter]
disabled = false
enableDNT = true
simple = true
[privacy.vimeo]
disabled = false
simple = true
[privacy.youtube]
disabled = false
privacyEnhanced = true
[services.instagram]
disableInlineCSS = true
[services.twitter]
disableInlineCSS = true
[taxonomies]
category = "categories"
series = "series"
tag = "tags"
disqusShortname = "stochasticprocesses"
[markup.goldmark.renderer]
unsafe= true
katex= true
